
import { getSiteSettings } from "@/services/settingsService";
import type { Metadata } from 'next';
import { schoolConfig } from "@/lib/config";

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Our policies and procedures on the collection, use and disclosure of your information when you use our service.',
};


export default async function PrivacyPolicyPage() {
    const settings = await getSiteSettings();
    const appUrl = schoolConfig.appBaseUrl;

    return (
        <div className="container mx-auto max-w-4xl px-4 md:px-6 py-12 md:py-16">
            <article className="space-y-4 text-foreground">
                <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl">Privacy Policy</h1>
                <p className="text-muted-foreground">Last updated: July 08, 2025</p>
                <p className="leading-7 [&:not(:first-child)]:mt-6">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                <p className="leading-7 [&:not(:first-child)]:mt-6">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                
                <h2 className="text-3xl font-semibold tracking-tight border-b pb-2 mt-10">Interpretation and Definitions</h2>
                <h3 className="text-2xl font-semibold tracking-tight mt-6">Interpretation</h3>
                <p className="leading-7 [&:not(:first-child)]:mt-6">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                <h3 className="text-2xl font-semibold tracking-tight mt-6">Definitions</h3>
                <p className="leading-7 [&:not(:first-child)]:mt-6">For the purposes of this Privacy Policy:</p>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to {settings.schoolName}, {settings.address}.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Country</strong> refers to: Bihar,  India</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website</strong> refers to {settings.schoolName}, accessible from <a href={appUrl} rel="external nofollow noopener" target="_blank" className="font-medium text-primary underline underline-offset-4">{appUrl}</a></li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>

                <h2 className="text-3xl font-semibold tracking-tight border-b pb-2 mt-10">Collecting and Using Your Personal Data</h2>
                <h3 className="text-2xl font-semibold tracking-tight mt-6">Types of Data Collected</h3>
                <h4 className="text-xl font-semibold tracking-tight mt-4">Personal Data</h4>
                <p className="leading-7 [&:not(:first-child)]:mt-6">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                </ul>

                <h4 className="text-xl font-semibold tracking-tight mt-4">Usage Data</h4>
                <p className="leading-7 [&:not(:first-child)]:mt-6">Usage Data is collected automatically when using the Service.</p>
                <p className="leading-7 [&:not(:first-child)]:mt-6">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p className="leading-7 [&:not(:first-child)]:mt-6">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                <p className="leading-7 [&:not(:first-child)]:mt-6">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                
                <h4 className="text-xl font-semibold tracking-tight mt-4">Tracking Technologies and Cookies</h4>
                <p className="leading-7 [&:not(:first-child)]:mt-6">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                    <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                    <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                </ul>
                <p className="leading-7 [&:not(:first-child)]:mt-6">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

                <h3 className="text-2xl font-semibold tracking-tight mt-6">Use of Your Personal Data</h3>
                <p className="leading-7 [&:not(:first-child)]:mt-6">The Company may use Personal Data for the following purposes:</p>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                    <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                    <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                    <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                    <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                    <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                    <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                    <li><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                </ul>

                <h3 className="text-2xl font-semibold tracking-tight mt-6">Security of Your Personal Data</h3>
                <p className="leading-7 [&:not(:first-child)]:mt-6">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                
                <h2 className="text-3xl font-semibold tracking-tight border-b pb-2 mt-10">GDPR Privacy</h2>
                <h3 className="text-2xl font-semibold tracking-tight mt-6">Legal Basis for Processing Personal Data under GDPR</h3>
                <p className="leading-7 [&:not(:first-child)]:mt-6">We may process Personal Data under the following conditions:</p>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                    <li><strong>Consent:</strong> You have given Your consent for processing Personal Data for one or more specific purposes.</li>
                    <li><strong>Performance of a contract:</strong> Provision of Personal Data is necessary for the performance of an agreement with You and/or for any pre-contractual obligations thereof.</li>
                    <li><strong>Legal obligations:</strong> Processing Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</li>
                    <li><strong>Vital interests:</strong> Processing Personal Data is necessary in order to protect Your vital interests or of another natural person.</li>
                    <li><strong>Public interests:</strong> Processing Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</li>
                    <li><strong>Legitimate interests:</strong> Processing Personal Data is necessary for the purposes of the legitimate interests pursued by the Company.</li>
                </ul>
                <h3 className="text-2xl font-semibold tracking-tight mt-6">Your Rights under the GDPR</h3>
                <p className="leading-7 [&:not(:first-child)]:mt-6">You have the right under this Privacy Policy, and by law if You are within the EU, to:</p>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                    <li><strong>Request access to Your Personal Data.</strong> The right to access, update or delete the information We have on You.</li>
                    <li><strong>Request correction of the Personal Data that We hold about You.</strong> You have the right to have any incomplete or inaccurate information We hold about You corrected.</li>
                    <li><strong>Object to processing of Your Personal Data.</strong> This right exists where We are relying on a legitimate interest as the legal basis for Our processing.</li>
                    <li><strong>Request erasure of Your Personal Data.</strong> You have the right to ask Us to delete or remove Personal Data when there is no good reason for Us to continue processing it.</li>
                    <li><strong>Request the transfer of Your Personal Data.</strong> We will provide to You, or to a third-party You have chosen, Your Personal Data in a structured, commonly used, machine-readable format.</li>
                    <li><strong>Withdraw Your consent.</strong> You have the right to withdraw Your consent on using your Personal Data.</li>
                </ul>

                <h2 className="text-3xl font-semibold tracking-tight border-b pb-2 mt-10">CCPA/CPRA Privacy Notice</h2>
                <p className="leading-7 [&:not(:first-child)]:mt-6">This section for California residents supplements the information contained in Our Privacy Policy and it applies solely to all visitors, users, and others who reside in the State of California.</p>
                <h3 className="text-2xl font-semibold tracking-tight mt-6">Your Rights under the CCPA/CPRA</h3>
                <p className="leading-7 [&:not(:first-child)]:mt-6">Under this Policy, and by law, if you are a resident of California, you have the following rights:</p>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                    <li><strong>The right to notice.</strong> You have the right to be notified which categories of Personal Data are being collected and the purposes for which the Personal Data is being used.</li>
                    <li><strong>The right to request.</strong> Under CCPA/CPRA, you have the right to request that We disclose information to you about Our collection, use, sale, disclosure for business purposes and share of personal information.</li>
                    <li><strong>The right to say no to the sale or sharing of Personal Data (opt-out).</strong> You have the right to direct Us that We do not sell Your personal information. To submit an opt-out request please contact Us.</li>
                    <li><strong>The right to correct.</strong> You have the right to request the correction of any inaccurate personal information We hold about You.</li>
                    <li><strong>The right to limit the use and disclosure of sensitive personal information.</strong> You have the right to request to limit the use or disclosure of sensitive personal information.</li>
                    <li><strong>The right to delete Personal Data.</strong> You have the right to request the deletion of Your Personal Data, subject to certain exceptions.</li>
                    <li><strong>The right not to be discriminated against.</strong> You have the right not to be discriminated against for exercising any of Your consumer's rights.</li>
                </ul>

                <h2 className="text-3xl font-semibold tracking-tight border-b pb-2 mt-10">Changes to this Privacy Policy</h2>
                <p className="leading-7 [&:not(:first-child)]:mt-6">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                
                <h2 className="text-3xl font-semibold tracking-tight border-b pb-2 mt-10">Contact Us</h2>
                <p className="leading-7 [&:not(:first-child)]:mt-6">If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                    <li>By email: <a href={`mailto:${settings.contactEmail}`} className="font-medium text-primary underline underline-offset-4">{settings.contactEmail}</a></li>
                    <li>By visiting this page on our website: <a href="/contact" rel="external nofollow noopener" target="_blank" className="font-medium text-primary underline underline-offset-4">Contact Us</a></li>
                    <li>By phone number: {settings.phone}</li>
                    <li>By mail: {settings.address}</li>
                </ul>
            </article>
        </div>
    );
}
